<?php

use Illuminate\Database\Seeder;

class InitMOrganisasiTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('m_organisasi')->delete();
        
        \DB::table('m_organisasi')->insert(array (
            0 => 
            array (
                'id' => 11,
                'pid' => NULL,
                'nama' => 'Dinas Kesehatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.02.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            1 => 
            array (
                'id' => 12,
                'pid' => NULL,
                'nama' => 'Dinas Bina Marga Dan Penataan Ruang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.03.0.00.0.00.10',
                'level' => 0,
                'jabatans' => NULL,
            ),
            2 => 
            array (
                'id' => 13,
                'pid' => NULL,
                'nama' => 'Dinas Sumber Daya Air',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.03.0.00.0.00.11',
                'level' => 0,
                'jabatans' => NULL,
            ),
            3 => 
            array (
                'id' => 14,
                'pid' => NULL,
                'nama' => 'Dinas Perumahan Dan Permukiman',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.04.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            4 => 
            array (
                'id' => 15,
                'pid' => NULL,
                'nama' => 'Satuan Polisi Pamong Praja',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.05.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            5 => 
            array (
                'id' => 16,
                'pid' => NULL,
                'nama' => 'Badan Penanggulangan Bencana Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.05.0.00.0.00.04',
                'level' => 0,
                'jabatans' => NULL,
            ),
            6 => 
            array (
                'id' => 18,
                'pid' => NULL,
                'nama' => 'Dinas Sosial',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '1.06.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            7 => 
            array (
                'id' => 19,
                'pid' => NULL,
                'nama' => 'Dinas Tenaga Kerja Dan Transmigrasi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.07.2.32.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            8 => 
            array (
                'id' => 20,
                'pid' => NULL,
                'nama' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Dan Keluarga Berencana',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.08.2.14.0.00.02',
                'level' => 0,
                'jabatans' => NULL,
            ),
            9 => 
            array (
                'id' => 21,
                'pid' => NULL,
                'nama' => 'Dinas Ketahanan Pangan dan Peternakan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.09.2.27.0.00.02',
                'level' => 0,
                'jabatans' => NULL,
            ),
            10 => 
            array (
                'id' => 22,
                'pid' => NULL,
                'nama' => 'Dinas Lingkungan Hidup',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.11.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            11 => 
            array (
                'id' => 23,
                'pid' => NULL,
                'nama' => 'Dinas Kependudukan Dan Pencatatan Sipil',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.12.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            12 => 
            array (
                'id' => 24,
                'pid' => NULL,
                'nama' => 'Dinas Pemberdayaan Masyarakat Dan Desa',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.13.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            13 => 
            array (
                'id' => 25,
                'pid' => NULL,
                'nama' => 'Dinas Perhubungan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.15.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            14 => 
            array (
                'id' => 26,
                'pid' => NULL,
                'nama' => 'Dinas Komunikasi Dan Informatika',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.16.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            15 => 
            array (
                'id' => 27,
                'pid' => NULL,
                'nama' => 'Dinas Koperasi Dan Usaha Kecil',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.17.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            16 => 
            array (
                'id' => 28,
                'pid' => NULL,
                'nama' => 'Dinas Penanaman Modal Dan Perizinan Terpadu Satu Pintu',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.18.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            17 => 
            array (
                'id' => 29,
                'pid' => NULL,
                'nama' => 'Dinas Pemuda Dan Olahraga',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.19.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            18 => 
            array (
                'id' => 30,
                'pid' => NULL,
                'nama' => 'Dinas Perpustakaan Dan Kearsipan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '2.23.2.24.0.00.02',
                'level' => 0,
                'jabatans' => NULL,
            ),
            19 => 
            array (
                'id' => 31,
                'pid' => NULL,
                'nama' => 'Dinas Kelautan dan Perikanan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.25.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            20 => 
            array (
                'id' => 32,
                'pid' => NULL,
                'nama' => 'Dinas Pariwisata dan Kebudayaan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.26.2.22.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            21 => 
            array (
                'id' => 33,
                'pid' => NULL,
                'nama' => 'Dinas Tanaman Pangan Dan Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.27.0.00.0.00.04',
                'level' => 0,
                'jabatans' => NULL,
            ),
            22 => 
            array (
                'id' => 34,
                'pid' => NULL,
                'nama' => 'Dinas Perkebunan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.27.0.00.0.00.06',
                'level' => 0,
                'jabatans' => NULL,
            ),
            23 => 
            array (
                'id' => 35,
                'pid' => NULL,
                'nama' => 'Dinas Kehutanan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.28.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            24 => 
            array (
                'id' => 36,
                'pid' => NULL,
                'nama' => 'Dinas Energi dan Sumber Daya Mineral',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.29.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            25 => 
            array (
                'id' => 37,
                'pid' => NULL,
                'nama' => 'Dinas Perindustrian dan Perdagangan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '3.31.3.30.0.00.02',
                'level' => 0,
                'jabatans' => NULL,
            ),
            26 => 
            array (
                'id' => 38,
                'pid' => NULL,
                'nama' => 'Badan Perencanaan Pembangunan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '4.01.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            27 => 
            array (
                'id' => 40,
                'pid' => NULL,
                'nama' => 'Badan Pendapatan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '4.02.0.00.0.00.03',
                'level' => 0,
                'jabatans' => NULL,
            ),
            28 => 
            array (
                'id' => 41,
                'pid' => NULL,
                'nama' => 'Badan Kepegawaian Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '4.03.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            29 => 
            array (
                'id' => 44,
                'pid' => NULL,
                'nama' => 'Sekretariat Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '5.01.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            30 => 
            array (
                'id' => 46,
                'pid' => 10,
                'nama' => 'Cabang Dinas Pendidikan 1',
                'alamat' => 'test',
                'aktif' => 0,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-20',
                'kode' => '1.01.0.00.0.00.03',
                'level' => 1,
                'jabatans' => NULL,
            ),
            31 => 
            array (
                'id' => 17,
                'pid' => 13,
                'nama' => 'Badan Kesatuan Bangsa dan Politik',
                'alamat' => 'sdsad',
                'aktif' => 0,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-27',
                'kode' => '6.01.0.00.0.00.01',
                'level' => 0,
                'jabatans' => '1,5',
            ),
            32 => 
            array (
                'id' => 10,
                'pid' => NULL,
                'nama' => 'Dinas Pendidikan',
                'alamat' => NULL,
                'aktif' => 0,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-11-03',
                'kode' => '1.01.0.00.0.00.01',
                'level' => 0,
                'jabatans' => '1,4',
            ),
            33 => 
            array (
                'id' => 42,
                'pid' => NULL,
                'nama' => 'Badan Pengembangan Sumber Daya Manusia',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '4.04.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            34 => 
            array (
                'id' => 43,
                'pid' => NULL,
                'nama' => 'Badan Penelitian dan Pengembangan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '4.05.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            35 => 
            array (
                'id' => 45,
                'pid' => NULL,
                'nama' => 'Sekretariat Dewan Perwakilan Rakyat Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '5.02.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            36 => 
            array (
                'id' => 47,
                'pid' => NULL,
                'nama' => 'Badan Penghubung',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-10-19',
                'kode' => '4.06.0.00.0.00.01',
                'level' => 0,
                'jabatans' => NULL,
            ),
            37 => 
            array (
                'id' => 48,
                'pid' => 10,
                'nama' => 'Cabang Dinas Pendidikan 2',
                'alamat' => NULL,
                'aktif' => 0,
                'created_at' => '2019-10-20',
                'updated_at' => '2019-10-20',
                'kode' => '1.01.0.00.0.00.02',
                'level' => 1,
                'jabatans' => NULL,
            ),
            38 => 
            array (
                'id' => 49,
                'pid' => NULL,
                'nama' => 'Cabang Kosong',
                'alamat' => 'test',
                'aktif' => NULL,
                'created_at' => '2019-10-21',
                'updated_at' => '2019-10-21',
                'kode' => '1234123',
                'level' => 1,
                'jabatans' => NULL,
            ),
            39 => 
            array (
                'id' => 50,
                'pid' => NULL,
                'nama' => 'Cabang Sub',
                'alamat' => '3123',
                'aktif' => NULL,
                'created_at' => '2019-10-21',
                'updated_at' => '2019-10-21',
                'kode' => '41231',
                'level' => 2,
                'jabatans' => NULL,
            ),
            40 => 
            array (
                'id' => 51,
                'pid' => 17,
                'nama' => 'Cabang Badan Kesatuan Bangsa',
                'alamat' => 'sfdasf',
                'aktif' => 1,
                'created_at' => '2019-10-27',
                'updated_at' => '2019-10-27',
                'kode' => '3124123',
                'level' => NULL,
                'jabatans' => '1,5',
            ),
            41 => 
            array (
                'id' => 52,
                'pid' => 51,
                'nama' => 'SMA Cabang Badan Kesatuan',
                'alamat' => 'sadsad',
                'aktif' => NULL,
                'created_at' => '2019-10-27',
                'updated_at' => '2019-10-27',
                'kode' => '14123123',
                'level' => NULL,
                'jabatans' => '1,6,7',
            ),
            42 => 
            array (
                'id' => 53,
                'pid' => NULL,
                'nama' => 'BPKAD',
                'alamat' => NULL,
                'aktif' => 0,
                'created_at' => '2019-10-28',
                'updated_at' => '2019-10-28',
                'kode' => '123456789',
                'level' => NULL,
                'jabatans' => '8,3,4,5,7',
            ),
            43 => 
            array (
                'id' => 54,
                'pid' => NULL,
                'nama' => 'SEKDA',
                'alamat' => NULL,
                'aktif' => 0,
                'created_at' => '2019-10-28',
                'updated_at' => '2019-10-28',
                'kode' => '123',
                'level' => NULL,
                'jabatans' => '1',
            ),
            44 => 
            array (
                'id' => 39,
                'pid' => NULL,
                'nama' => 'Badan Pengelolaan Keuangan Dan Aset Daerah',
                'alamat' => NULL,
                'aktif' => 0,
                'created_at' => '2019-10-19',
                'updated_at' => '2019-11-05',
                'kode' => '4.02.0.00.0.00.02',
                'level' => 0,
                'jabatans' => '1,8,4',
            ),
        ));
        
        
    }
}