<?php

use Illuminate\Database\Seeder;

class InitMOrganisasiTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('m_organisasi')->delete();
        
        \DB::table('m_organisasi')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pid' => NULL,
                'nama' => 'Dinas Pendidikan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah I',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah II',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah III',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah IV',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah V',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah VI',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah VII',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah VIII',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah IX',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.09',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah X',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.10',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah XI',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.11',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah XII',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.12',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Pendidikan Wilayah XIII',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.13',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'pid' => NULL,
                'nama' => 'Balai Pengembangan Pendidik dan Tenaga Kependidikan Umum, Kejuruan, Khusus dan Layanan Khusus',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.14',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'pid' => NULL,
                'nama' => 'Balai Teknologi Informasi dan Komunikasi Pendidikan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.01.0.00.0.00.01.15',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'pid' => NULL,
                'nama' => 'Dinas Kesehatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'pid' => NULL,
                'nama' => 'UPTD Laboratorium Kesehatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'pid' => NULL,
                'nama' => 'UPTD Pelatihan Kesehatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Jiwa, rumah sakit khusus',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Paru, rumah sakit khusus',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Umum Daerah Al Ihsan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Umum Daerah Jampang Kulon Sukabumi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Umum Daerah Kesehatan Kerja Provinsi Jawa Barat',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Umum Daerah Pameungpeuk Garut',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.02.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'pid' => NULL,
                'nama' => 'Dinas Bina Marga Dan Penataan Ruang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Jalan dan Jembatan Wilayah Pelayanan I',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Jalan dan Jembatan Wilayah Pelayanan II',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Jalan dan Jembatan Wilayah Pelayanan III',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Jalan dan Jembatan Wilayah Pelayanan IV',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Jalan dan Jembatan Wilayah Pelayanan V',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Jalan dan Jembatan Wilayah Pelayanan VI',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'pid' => NULL,
                'nama' => 'UPTD Laboratorium Bahan Konstruksi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.10.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'pid' => NULL,
                'nama' => 'Dinas Sumber Daya Air',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sumber Daya Air Wilayah Sungai Ciliwung-Cisadane',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sumber Daya Air Wilayah Sungai Cisade-Cibareno',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sumber Daya Air Wilayah Sungai Citarum',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sumber Daya Air Wilayah Sungai Cimanuk-Cisanggarung',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sumber Daya Air Wilayah Sungai Citanduy',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sumber Daya Air Wilayah Sungai Ciwulan-Cilaki',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.03.0.00.0.00.11.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'pid' => NULL,
                'nama' => 'Dinas Perumahan Dan Permukiman',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.04.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan dan Pelayanan Perumahan Jawa Barat',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.04.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'pid' => NULL,
                'nama' => 'Satuan Polisi Pamong Praja',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.05.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'pid' => NULL,
                'nama' => 'Badan Penanggulangan Bencana Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.05.0.00.0.00.04.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'pid' => NULL,
                'nama' => 'Badan Kesatuan Bangsa dan Politik',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '6.01.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'pid' => NULL,
                'nama' => 'Dinas Sosial',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'pid' => NULL,
                'nama' => 'UPTD Panti Pemberdayaan Sosial Bina Remaja',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'pid' => NULL,
                'nama' => 'UPTD Pengembangan dan Pelatihan Kesejahteraan Sosial',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'pid' => NULL,
                'nama' => 'UPTD Panti Sosial Rehabilitasi Anak Berhadapan dengan Hukum',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'pid' => NULL,
                'nama' => 'UPTD Panti Sosial Rehabilitasi Anak Membutuhkan Perlindungan Khusus',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'pid' => NULL,
                'nama' => 'UPTD Panti Rehabilitasi Sosial Bina Karya',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'pid' => NULL,
                'nama' => 'UPTD Panti Sosial Rehabilitasi Penyandang Disabilitas Mental Sensorik Netra Rungu Wicara Tubuh',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'pid' => NULL,
                'nama' => 'UPTD Panti Sosial Rehabilitasi Tuna Sosial',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'pid' => NULL,
                'nama' => 'UPTD Panti Sosial Rehabilitasi Lanjut Usia dan Pemeliharaan Makam Pahlawan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '1.06.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'pid' => NULL,
                'nama' => 'Dinas Tenaga Kerja Dan Transmigrasi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Ketenagakerjaan Wilayah I Bogor',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Ketenagakerjaan Wilayah II Bekasi dan Kerawang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Ketenagakerjaan Wilayah III Cirebon',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Ketenagakerjaan Wilayah IV Bandung',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Ketenagakerjaan Wilayah V Tasikmalaya',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'pid' => NULL,
                'nama' => 'UPTD Balai Latihan Kerja Kompetensi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'pid' => NULL,
                'nama' => 'UPTD Balai Latihan Kerja Pekerja Migran Indonesia',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'pid' => NULL,
                'nama' => 'UPTD Balai Latihan Kerja Mandiri',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.07.2.32.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'pid' => NULL,
                'nama' => 'Dinas Pemberdayaan Perempuan, Perlindungan Anak, Dan Keluarga Berencana',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.08.2.14.0.00.02.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'pid' => NULL,
                'nama' => 'Dinas Ketahanan Pangan dan Peternakan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengawasan Mutu dan Keamanan Pangan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengujian Mutu dan Keamanan Pakan/Bahan Pakan Cikole Lembang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pelatihan Peternakan dan Ketahan Pangan Cikole Lembang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'pid' => NULL,
                'nama' => 'UPTD Balai Perbibitan dan Pengembangan Insemenasi Buatan Ternak Sapi Potong Ciamis',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengembangan Perbibitan Ternak Unggas Jatiwangi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengembangan Perbibitan Ternak Domba dan Kambing Margawati',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'pid' => NULL,
                'nama' => 'UPTD Balai Kesehatan Hewan dan Kesehatan Masyarakat Veteriner',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'pid' => NULL,
                'nama' => 'UPTD Balai Perbibitan dan Pengembangan Inseminasi Buatan Ternak Sapi Perah Bunikasih',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'pid' => NULL,
                'nama' => 'UPTD Rumah Sakit Hewan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.09',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengembangan Ternak Sapi Perah dan Hijauan Pakan Ternak Cikole Lembang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.09.2.27.0.00.02.10',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'pid' => NULL,
                'nama' => 'Dinas Lingkungan Hidup',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.11.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'pid' => NULL,
                'nama' => 'UPTD Laboratorium Lingkungan Hidup',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.11.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Sampah TPA/TPST Regional',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.11.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'pid' => NULL,
                'nama' => 'Dinas Kependudukan Dan Pencatatan Sipil',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.12.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'pid' => NULL,
                'nama' => 'Dinas Pemberdayaan Masyarakat Dan Desa',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.13.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'pid' => NULL,
                'nama' => 'Dinas Perhubungan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Prasarana Perhubungan Lalu Lintas dan Angkutan Jalan Wilayah I',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Prasarana Perhubungan Lalu Lintas dan Angkutan Jalan Wilayah II',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Prasarana Perhubungan Lalu Lintas dan Angkutan Jalan Wilayah III',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Prasarana Perhubungan Lalu Lintas dan Angkutan Jalan Wilayah IV',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'pid' => NULL,
                'nama' => 'UPTD Pelayanan Jasa Kebandarudaraan Nusawiru',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Prasarana Perhubungan Lalu Lintas Angkutan Sungai, Danau dan Penyebrangan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'pid' => NULL,
                'nama' => 'UPTD Pengelolaan Prasarana Perhubungan Pelabuhan Laut',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.15.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'pid' => NULL,
                'nama' => 'Dinas Komunikasi Dan Informatika',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.16.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'pid' => NULL,
                'nama' => 'Dinas Koperasi Dan Usaha Kecil',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.17.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'pid' => NULL,
                'nama' => 'UPTD Pendidikan dan Pelatihan Perkoperasian dan Wirausaha',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.17.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'pid' => NULL,
                'nama' => 'Dinas Penanaman Modal Dan Perizinan Terpadu Satu Pintu',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.18.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'pid' => NULL,
                'nama' => 'Dinas Pemuda Dan Olahraga',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.19.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'pid' => NULL,
                'nama' => 'Dinas Perpustakaan Dan Kearsipan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '2.23.2.24.0.00.02.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'pid' => NULL,
                'nama' => 'Dinas Kelautan dan Perikanan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kelautan dan Perikanan Wilayah Selatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kelautan dan Perikanan Wilayah Utara',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'pid' => NULL,
                'nama' => 'UPTD Pelabuhan Perikanan Cilautereun',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'pid' => NULL,
                'nama' => 'UPTD Pelabuhan Perikanan Muara Ciasem',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'pid' => NULL,
                'nama' => 'UPTD Pengujian dan Penerapan Mutu Produk Perikanan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Sumber Daya Kelautan dan Perikanan Wilayah Selatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'pid' => NULL,
                'nama' => 'UPTD Pengawasan Sumber Daya Kelautan dan Perikanan Wilayah Utara',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'pid' => NULL,
                'nama' => 'UPTD Perikanan Air Payau dan Laut Wilayah Selatan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'pid' => NULL,
                'nama' => 'UPTD Perikanan Air Payau dan Laut Wilayah Utara',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.25.0.00.0.00.01.09',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'pid' => NULL,
                'nama' => 'Dinas Pariwisata dan Kebudayaan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.26.2.22.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'pid' => NULL,
                'nama' => 'UPTD Pengelola Kebudayaan Daerah Jawa Barat',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.26.2.22.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'pid' => NULL,
                'nama' => 'Dinas Tanaman Pangan Dan Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'pid' => NULL,
                'nama' => 'UPTD Balai Benih Kentang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'pid' => NULL,
                'nama' => 'UPTD Balai Benih Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'pid' => NULL,
                'nama' => 'UPTD Balai Benih Padi dan Palawija',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengawasan dan Sertifikasi Benih Tanaman Pangan dan Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'pid' => NULL,
                'nama' => 'UPTD Balai Perlindungan Tanaman Pangan dan Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pelatihan Tanaman Pangan dan Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'pid' => NULL,
                'nama' => 'UPT Balai Pengembangan Mekanisasi Tanaman Pangan dan Hortikultura',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.04.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'pid' => NULL,
                'nama' => 'Dinas Perkebunan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.06.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengembangan dan Produksi Benih Perkebunan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.06.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengawasan dan Sertfikasi Benih Perkebunan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.06.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'pid' => NULL,
                'nama' => 'UPTD Balai Perlindungan Perkebunan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.27.0.00.0.00.06.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'pid' => NULL,
                'nama' => 'Dinas Kehutanan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah I',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah II',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah III',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah IV',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah V',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah VI',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah VII',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah VIII',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Kehutanan Wilayah IX',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.09',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'pid' => NULL,
            'nama' => 'UPTD Taman Hutan Raya (TAHURA) Ir.H. Djuanda',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.10',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'pid' => NULL,
                'nama' => 'UPTD Sertifikasi dan Perbenihan Tanaman Hutan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.11',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'pid' => NULL,
                'nama' => 'UPTD Pelayanan Pengolahan Hasil Hutan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.28.0.00.0.00.01.12',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'pid' => NULL,
                'nama' => 'Dinas Energi dan Sumber Daya Mineral',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah I Cianjur',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah II Bogor',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah III Purwakarta',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah IV Bandung',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah V Sumedang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah VI Tasikmalaya',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'pid' => NULL,
                'nama' => 'Cabang Dinas Energi dan Sumber Daya Mineral Wilayah VII Cirebon',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'pid' => NULL,
                'nama' => 'UPTD Laboratorium Energi dan Sumber Daya Mineral',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.29.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'pid' => NULL,
                'nama' => 'Dinas Perindustrian dan Perdagangan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'pid' => NULL,
                'nama' => 'UPTD Industri Logam',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'pid' => NULL,
                'nama' => 'UPTD Industri Pangan, Olahan dan Kemasan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengujian dan Sertifikasi Mutu Barang Logam dan Elektronika Karawang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengujian dan Sertifikasi Mutu Barang Keramik dan Tabung Gas Bogor',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengujian dan Sertifikasi Mutu Barang Air Minum dalam Kemasan Cirebon',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'pid' => NULL,
                'nama' => 'UPTD Balai Pengujian dan Sertifikasi Mutu Barang Agro Bandung',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '3.31.3.30.0.00.02.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'pid' => NULL,
                'nama' => 'Badan Perencanaan Pembangunan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.01.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'pid' => NULL,
                'nama' => 'Badan Pengelolaan Keuangan Dan Aset Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.02.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'pid' => NULL,
                'nama' => 'Badan Pendapatan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Depok I',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Depok II Cinere',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Bogor',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Bogor',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Sukabumi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Sukabumi I Cibadak',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Sukabumi II Pelabuhan Ratu',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Cianjur',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Bekasi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.09',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Bekasi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.10',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Karawang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.11',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Purwakarta',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.12',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Subang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.13',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Cirebon',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.14',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Cirebon I Sumber',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.15',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Cirebon II Ciledug',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.16',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Indramayu I',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.17',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Indramayu II Haurgeulis',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.18',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Kuningan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.19',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Majalengka',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.20',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Bandung I Pajajaran',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.21',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Bandung II Kawaluyaan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.22',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Bandung III Soekarno Hatta',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.23',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Bandung Barat',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.24',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Bandung I Rancaekek',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.25',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Bandung II Soreang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.26',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Sumedang',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.27',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Garut',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.28',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Tasikmalaya',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.29',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Tasikmalaya',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.30',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Ciamis',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.31',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kabupaten Pangandaran',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.32',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Cimahi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.33',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Pengelolaan Pendapatan Daerah Wilayah Kota Banjar',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.34',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'pid' => NULL,
                'nama' => 'UPTD Pusat Layanan Operasional Pendapatan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.02.0.00.0.00.03.35',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'pid' => NULL,
                'nama' => 'Badan Kepegawaian Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.03.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'pid' => NULL,
                'nama' => 'Badan Pengembangan Sumber Daya Manusia',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.04.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'pid' => NULL,
                'nama' => 'Badan Penelitian dan Pengembangan Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.05.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'pid' => NULL,
                'nama' => 'Sekretariat Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'pid' => NULL,
                'nama' => 'Biro Pemerintahan dan Kerjasama',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.01',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'pid' => NULL,
                'nama' => 'Biro Hukum dan Hak Asasi Manusia',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.02',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'pid' => NULL,
                'nama' => 'Biro Pelayanan dan Pengembangan Sosial',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.03',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'pid' => NULL,
                'nama' => 'Biro Badan Usaha Milik Daerah dan Investasi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.04',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            193 => 
            array (
                'id' => 194,
                'pid' => NULL,
                'nama' => 'Biro Perekonomian',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.05',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            194 => 
            array (
                'id' => 195,
                'pid' => NULL,
                'nama' => 'Biro Pengadaan Barang/Jasa',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.06',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            195 => 
            array (
                'id' => 196,
                'pid' => NULL,
                'nama' => 'Biro organisasi',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.07',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            196 => 
            array (
                'id' => 197,
                'pid' => NULL,
                'nama' => 'Biro Hubungan Masyarakat dan Keprotokolan',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.08',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            197 => 
            array (
                'id' => 198,
                'pid' => NULL,
                'nama' => 'Biro Umum',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.01.0.00.0.00.01.09',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            198 => 
            array (
                'id' => 199,
                'pid' => NULL,
                'nama' => 'Sekretariat Dewan Perwakilan Rakyat Daerah',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '5.02.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            199 => 
            array (
                'id' => 200,
                'pid' => NULL,
                'nama' => 'Inspektorat',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '7.01.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            200 => 
            array (
                'id' => 201,
                'pid' => NULL,
                'nama' => 'Badan Penghubung',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '4.06.0.00.0.00.01.00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
            
            201 => 
            array (
                'id' => 202,
                'pid' => NULL,
                'nama' => 'Badan Pengelolaan Keuangan Dan Aset Daerah
                Kabid BMD ( BPKAD )',
                'alamat' => NULL,
                'aktif' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'kode' => '00',
                'level' => NULL,
                'jabatans' => NULL,
                'setting' => NULL,
            ),
        ));
        
        
    }
}